In [25]:
import torch
import numpy as np

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.size()

torch.Size([12])

In [8]:
x = x.reshape(3,4)

In [9]:
x.shape

torch.Size([3, 4])

In [10]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(2,3,4)

tensor([[[ 1.3355,  1.3001, -0.5256, -1.4448],
         [ 0.5312,  0.6157,  1.6351, -0.1917],
         [ 0.1461, -1.3675,  0.1569, -0.4738]],

        [[-0.3177, -0.0128,  1.5322,  2.3135],
         [-0.7939, -1.2252, -1.3810,  1.4897],
         [ 0.3325,  2.6735, -1.5707, -1.1694]]])

In [15]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [19]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [20]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [21]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [22]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
x.sum()

tensor(66.)

In [57]:
a = torch.arange(9).reshape((3, 1, 3))
b = torch.arange(6).reshape((1, 2, 3))
a, b

(tensor([[[0, 1, 2]],
 
         [[3, 4, 5]],
 
         [[6, 7, 8]]]),
 tensor([[[0, 1, 2],
          [3, 4, 5]]]))

In [58]:
a + b

tensor([[[ 0,  2,  4],
         [ 3,  5,  7]],

        [[ 3,  5,  7],
         [ 6,  8, 10]],

        [[ 6,  8, 10],
         [ 9, 11, 13]]])

In [37]:
a[1:3]

tensor([[1],
        [2]])

In [40]:
x = x.reshape(3,4)

In [41]:
x[1,2]=9

In [42]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [43]:
x[0:2, :] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [44]:
before = id(y)
y = y + x
before, id(y)

(4759814304, 4741108752)

In [47]:
z = torch.zeros_like(y)
z[:] = x + y
z

tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])

In [48]:
z.numpy()

array([[26., 25., 28., 27.],
       [25., 26., 27., 28.],
       [20., 21., 22., 23.]], dtype=float32)

In [50]:
a = torch.tensor([0.5])
a, a.item(), float(a), int(a)

(tensor([0.5000]), 0.5, 0.5, 0)

In [55]:
a = torch.tensor([1, 2, 3])
for x in a: print(x)

tensor(1)
tensor(2)
tensor(3)
